DATA:
  name: "CIFAR100"
  img_size: 32
  num_classes: 100
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "AC"
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [2]
  attn_d_loc: [1]
  z_dim: 80
  g_shared_dim: 128
  g_conv_dim: 96
  d_conv_dim: 96
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 1000
  info_type: "discrete"
  g_info_injection: "cBN"
  info_num_discrete_c: 1
  info_dim_discrete_c: 20
LOSS:
  adv_loss: "hinge"
  cond_lambda: 1.0
  infoGAN_loss_discrete_lambda: 1.0
