DATA:
  name: "Tiny_ImageNet"
  img_size: 32
  num_classes: 200
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [2]
  attn_d_loc: [1]
  z_dim: 80
  g_shared_dim: 128
  g_conv_dim: 96
  d_conv_dim: 96
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 4000
  info_type: "discrete"
  g_info_injection: "cBN"
  info_num_discrete_c: 1
  info_dim_discrete_c: 20
LOSS:
  adv_loss: "hinge"
  infoGAN_loss_discrete_lambda: 1.0
OPTIMIZATION:
  batch_size: 256
  g_lr: 0.0001
  d_lr: 0.0004
  beta1: 0.5
  beta2: 0.999
  d_updates_per_step: 1
  total_steps: 120000
  
