DATA:
  name: "Tiny_ImageNet"
  img_size: 32
  num_classes: 200
MODEL:
  g_cond_mtd: "W/O"
  d_cond_mtd: "W/O"
  apply_d_sn: True
LOSS:
  adv_loss: "hinge"
OPTIMIZATION:
  batch_size: 256
  g_lr: 0.0002
  d_lr: 0.0002
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 1
