DATA:
  name: "CelebA-HQ"
  img_size: 256
  num_classes: 1
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "W/O"
  d_cond_mtd: "W/O"
  apply_g_sn: True
  apply_d_sn: True
  z_dim: 140
  g_shared_dim: 128
  g_conv_dim: 96
  d_conv_dim: 96
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 20000
LOSS:
  adv_loss: "hinge"
  lecam_lambda: 0.01
  lecam_ema_start_iter: 1000
  lecam_ema_decay: 0.99
OPTIMIZATION:
  eval_batch_size: 64
  batch_size: 64
  g_lr: 0.00005
  d_lr: 0.0002
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 2
  total_steps: 200000
